twig:
    default_path: '%kernel.project_dir%/src/Views/Public/Resources/templates'
    # globals:
        # param: '@App\Domain\ParamsService'
    # paths:
        # 'email/default/templates': ~
        # 'backend/templates': 'admin'

when@test:
    twig:
        strict_variables: true
